wiki/encyclopedia/urls.py
from django.urls import path, re_path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("search", views.search, name="u_search"),
    path("create", views.create, name="u_create"),
    path("edit", views.edit, name="u_edit"),
    path("save", views.save, name="u_save"),
    path("random_entry", views.random_entry, name="u_random"), 
    path("<str:entry_name>", views.url_entry, name="u_entry"),
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
import markdown2
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django import forms
from . import util
import random

#Form that captures the search input from user
class NewSearchForm(forms.Form):
    query = forms.CharField(label="search string")

#Form that allows the user to edit or create, dependingo on the path taken by user
class NewCreateEditForm(forms.Form):
    entry_title = forms.CharField(label="entry title")
    entry_body  = forms.CharField(widget=forms.Textarea(attrs={'style': 'height: 200px;', 'title': 'Entry Body'}))


def index(request):
    # Get the URL parameter that was submitted from search form
    # search_term = request.GET.get('search_string', '')
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
    })

#This view displays a single entry
def url_entry(request, entry_name):
    file_text = util.get_entry(entry_name)

    if file_text is not None:
        file_text = markdown2.markdown(file_text)
        return render(request, "encyclopedia/entry.html", {
            "entry_name" : entry_name,
            "entry_text" : file_text,
            "entries": util.list_entries(),
        })
    else:
        return render(request, "encyclopedia/error.html", {
            "error_message": "This entry does not exist"
        })

#This view provides the logic for searching for a wiki entry based on user input
def search(request):
    entry_list = util.list_entries()
    matching_items = 0
    if request.method == "POST":
        form = NewSearchForm(request.POST)
        if form.is_valid():
            query = form.cleaned_data["query"]

            # get list of machting entries from the list, case insesitive search
            matching_items = [s for s in entry_list if query.lower() in s.lower()]

            #If query matches a value in the list, redirect user to entry page
            if query.lower() in map(str.lower, entry_list):
                return HttpResponseRedirect(reverse("encyclopedia:u_entry", kwargs={'entry_name':query}))
            #else find all matching entries and present the list to user on a search page
            elif len(matching_items) > 0:
                return render(request, "encyclopedia/search.html" , {
                    "search_term" : query,
                    "matching_items": matching_items,
                })
            else:
                return render(request, "encyclopedia/search.html" , {
                    "message": "No matches found. Please refine your search",
                })
        else:
            return render(request, "encyclopedia/search.html" , {
                "message": "asdfasfsafsfasdf",
            })
    else:
        return render(request, "encyclopedia/search.html" , {
            "message" : "Please use the search form to find relevant pages by title",
        })

#This view gets the entry name to be edited, gets the details of that entry and pre-populates the forms
#with the entry values
def edit(request):
    entry_name = request.GET.get('p', '')
    if request.method == "GET" and entry_name is not '' and entry_name in util.list_entries():
        file_text = util.get_entry(entry_name)
        return render(request, "encyclopedia/edit.html", {
            "edit_form": NewCreateEditForm(initial={"entry_title":entry_name, "entry_body":file_text}),
        })
    else:
        return render(request, "encyclopedia/error.html", {
            "error_message": "This entry does not exist or you got here in error."
        })

#This view renders an empty create form
def create(request):
    return render(request, "encyclopedia/create.html" , {
        "create_form": NewCreateEditForm(),
    })

#Save entry into storage.
def save(request):
    if request.method == "POST":
        referer = request.META['HTTP_REFERER']
        form = NewCreateEditForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["entry_title"]
            body = form.cleaned_data["entry_body"]
            #Only be able to create new entries that do not exist
            if ("create" in referer) and (title not in util.list_entries()):
                util.save_entry(title, body)
                return HttpResponseRedirect(reverse("encyclopedia:u_entry", kwargs={'entry_name':title}))
            #Only allow editing of existing entries
            elif ("edit" in referer) and (title in util.list_entries()):
                util.save_entry(title, body)
                return HttpResponseRedirect(reverse("encyclopedia:u_entry", kwargs={'entry_name':title}))
            else:
                return render(request, "encyclopedia/error.html", {
                    "error_message": "You can only create uniquely new entries or edit existing entries"
                })
        else:
            return render(request, "encyclopedia/error.html", {
                "error_message": "The form is not valid yet. Go back and edit values"
            })
    else:
        return render(request, "encyclopedia/error.html", {
            "error_message": "This page is not meant to be accessed directly."
        })


def random_entry(request):
    entries = util.list_entries()
    random_entry = entries[random.randint(0,len(entries)-1)]
    return HttpResponseRedirect(reverse("encyclopedia:u_entry", kwargs={'entry_name':random_entry}))

wiki/encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create New entry
{% endblock %}

{% block body %}
    <h1> Create a new entry </h1>

  <form action="{% url 'encyclopedia:u_save' %}" method="post">
      {% csrf_token %}
      {{create_form.as_p}}
      <input type="submit" value="Submit">
  </form>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit entry
{% endblock %}

{% block body %}
    <h1> Edit entry </h1>

  <form action="{% url 'encyclopedia:u_save' %}" method="post">
      {% csrf_token %}
      {{edit_form.as_p}}
      <input type="submit" value="Submit">
  </form>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{entry_name}}
{% endblock %}

{% block nav %}
  <div style="padding-left:5px;"> All Pages </div>
  {% for entry in entries %}
      <!-- Entry name is passed as url parameter -->
      <div class="navrow"><a href="{% url 'encyclopedia:u_entry' entry %}" class="dynamicNav">{{ entry }}</a></div>
  {% endfor %}
  <br>
{% endblock %}

{% block body %}
    <!-- Display body of entry -->
    {{entry_text|safe}}
    <a style="background-color:yellow;" href="{% url 'encyclopedia:u_edit' %}?p={{entry_name}}">Edit this wiki entry<a/>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Error Page
{% endblock %}

{% block body %}
    <h2>Error Page</h2>
    {{error_message}}
    <p> Please use links on left and navigate to right area </p>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <!-- Entry name is passed as url parameter -->
            <li><a href="{% url 'encyclopedia:u_entry' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:u_search' %}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="query" placeholder="Search Encyclopedia">
                </form>
                <div class="navrow">
                    <a href="{% url 'encyclopedia:index' %}" class="navitem">Home</a>
                </div>
                <div class="navrow">
                    <a href="{% url 'encyclopedia:u_create' %}" class="navitem">Create New Page</a>
                </div>
                <div class="navrow">
                    <a href="{% url 'encyclopedia:u_random' %}" class="navitem">Random Page</a>
                </div>

                <!-- Use this block to display list of entries only when on a single entry page -->
                {% block nav %}
                {% endblock %}

            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search Results
{% endblock %}

{% block body %}
    <h1> Search Results </h1>
    {% if search_term != None %}
        <p>You searched for : {{search_term}} </p>
        <p>Your search found {{matching_items|length}} matching items </p>

        <p> Use the links below to read more:
          <ul>
              {% for item in matching_items %}
                  <!-- Entry name is passed as url parameter -->
                  <li><a href="{% url 'encyclopedia:u_entry' item %}">{{ item }}</a></li>
              {% endfor %}
          </ul>
    {% else %}
        <p>{{message}}</p>
    {% endif %}

{% endblock %}