commerce/auctions/urls.py
from django.urls import path

from . import views

app_name = "auctions"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("listing/<int:listing_id>", views.listing_detail, name="u_listing_detail"),
    path("listing/create", views.create_listing, name="u_create_listing"),
    path("listing/<int:listing_id>/manage", views.manage_listing, name="u_manage_listing"),
    path("listing/<int:listing_id>/close", views.close_listing, name="u_close_listing"),
    path("watchlist", views.watchlist, name="u_watchlist"),
    path("watchlist/<int:watchlist_id>/unwatch_listing/<int:listing_id>", views.unwatch_listing, name="u_unwatch_listing"),
    path("watchlist/delete/<int:watchlist_id>", views.delete_watchlist, name="u_delete_watchlist"),
    path("add_bid", views.add_bid, name="u_add_bid"),
    path("listing/<int:listing_id>/add_comment", views.add_comment, name="u_add_comment"),
    path("listing/<int:listing_id>/add_to_watchlist", views.add_to_watchlist, name="u_add_to_watchlist"),
    path("categories", views.categories, name="u_categories"),
]

#    path("save", views.save_listing, name="u_save_listing"),

commerce/commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

commerce/auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    pass

class Category(models.Model):
    name = models.CharField(max_length=30)
    def __str__(self):
        return f"{self.name}"

#TODO - update cascade model for winner bid, category
class Listing(models.Model):
    title = models.CharField(max_length=30)
    description = models.TextField(max_length=200)
    photo_url = models.URLField(null=True, blank=True)
    starting_bid = models.PositiveIntegerField()
    bid_increment = models.PositiveIntegerField(default=1)
    current_bid = models.PositiveIntegerField(default=0)
    active = models.BooleanField(default=True)
    created = models.DateField(auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True, related_name="listings")
    by_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="my_listings")
    def __str__(self):
        return f"{self.id}: {self.title} / {self.photo_url} / {self.starting_bid} / {self.active}"

class Bid(models.Model):
    bid_value = models.PositiveIntegerField()
    winning_bid = models.BooleanField(default=False)
    by_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="bids_made")
    for_listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="bids_received")
    def __str__(self):
        return f"BidID={self.id}: BidValue={self.bid_value}: ListingID={self.for_listing.id}: WinningBid={self.winning_bid}"

class Watchlist(models.Model):
    name = models.CharField(max_length=30, default="")
    listings = models.ManyToManyField(Listing, blank=True, related_name="being_watched")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="watchlist")
    def __str__(self):
        return f"{self.id}: {self.name} {self.listings}"

class Comment(models.Model):
    content = models.TextField(max_length=200)
    by_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments_made")
    for_listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="comments")
    def __str__(self):
        return f"{self.id}: {self.content}"

commerce/auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponseBadRequest, HttpResponseRedirect, Http404
from django.shortcuts import render, redirect
from django.urls import reverse
from django.forms import ModelForm
from django.db.models import Max
from django.views.decorators.http import *
from django.contrib.auth.decorators import login_required
from django.contrib.sessions.models import Session
from django.contrib import messages
from .models import *

# Create the form based on the model already defined
class NewListingForm(ModelForm):
    class Meta:
        model = Listing
        fields = ['id', 'title', 'description', 'starting_bid', 'photo_url', 'category']

# Create the form based on the model already defined
class NewWatchlistForm(ModelForm):
    class Meta:
        model = Watchlist
        fields = ['name','user']

def index(request):
    return render(request, "auctions/index.html", {
        "listings": Listing.objects.filter(active=True).all(),
        "closed_listings": Listing.objects.filter(active=False).all()
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")


# Render the listing details
def listing_detail(request, listing_id):
    #l = listing_id
    l = Listing.objects.get(id=listing_id)
    #get next valid bid from utility function
    return render(request, "auctions/listing_detail.html", {
        "listing": l,
        "next_bid": get_next_bid(l),
    })


# Create a new listing
@login_required(login_url='/login')
def create_listing(request):
    path = request.META['PATH_INFO']
    if request.method == "GET":
        return render(request, "auctions/create_listing.html" , {
            "create_form": NewListingForm(),
        })
    elif request.method == "POST":
        saved_list_id = save_listing(request, "create_new")
        return HttpResponseRedirect(reverse("auctions:u_listing_detail", kwargs={'listing_id':saved_list_id}))


#TODO - see if we can disable the starting-bid field in edit form.
# Render the listing form with existing listing
@login_required(login_url='/login')
def manage_listing(request, listing_id):
    path = request.META['PATH_INFO']
    l = Listing.objects.get(id=listing_id)

    #Only allow editing of existing entries. Lets render the form on GET
    if request.method == "GET": #and "manage" in path
        is_editable = '' #Empty string means field is editable

        # if listing is not active, make form readonly
        if not l.active:
            is_editable = "disabled"

        # only allow the owner of user to edit an entry if entry is active
        if int(l.by_user.id) == int(request.session.get('_auth_user_id')):

            return render(request, "auctions/manage_listing.html" , {
                "listing" : l,
                "create_form": NewListingForm(instance=l),
            })
        else:
            return render(request, "auctions/error.html", {
                "error_message": "You cannot edit listings owned by someone else"
            })

    elif request.method == "POST" and "manage" in path:
        save_listing(request, "edit_existing", l)
        return HttpResponseRedirect(reverse("auctions:u_listing_detail", kwargs={'listing_id':listing_id}))


    else:
        return render(request, "auctions/error.html", {
            "error_message": "You can only create uniquely new entries or edit existing entries"
        })


#Close the listing, make the highest bidder the winner.
@login_required(login_url='/login')
def close_listing(request, listing_id):
    l = Listing.objects.get(id=listing_id)
    winning_bid = None

    # Set active status to false to close listing.
    if request.method == "POST" :
        l.active = False
        pass
        l.save()

        #Proceed further only if there are bids on this listing
        if l.bids_received.count() > 0:
            # Get max bid from all the bids on this listing
            max_bid_value = l.bids_received.aggregate(max_bid = Max("bid_value"))
            max_bid = max_bid_value['max_bid'] #This is the actual bid value

            #Use the max_bid value to find the winning bid
            winning_bid = l.bids_received.all().filter(bid_value=max_bid).first()

            #Update the bid to be the winning bid.
            Bid.objects.filter(id=winning_bid.id).update(
                winning_bid = True,
            )

    return HttpResponseRedirect(reverse("auctions:u_listing_detail", kwargs={'listing_id':listing_id}))


# Save listing changes when changes are posted from the form.
@login_required(login_url='/login')
def save_listing(request, action, listing=None):
    u = User.objects.get(pk=int(request.session.get('_auth_user_id')))

    if request.method == "POST":
        l = listing
        form = NewListingForm(request.POST)
        saved_listing_id = None

        if form.is_valid():
            title = form.cleaned_data["title"]
            description = form.cleaned_data["description"]
            starting_bid = form.cleaned_data["starting_bid"]
            photo_url = form.cleaned_data["photo_url"]
            category = form.cleaned_data["category"]
            by_user = u

            #if new listing, just save object and redirect
            if action == "create_new":
                saved_listing = Listing.objects.create (
                    title = title,
                    description = description,
                    starting_bid = starting_bid,
                    photo_url = photo_url,
                    category = category,
                    by_user = u )
                saved_listing_id = saved_listing.id
            #else existing listing, update object based on id
            elif action == "edit_existing":
                listing_id = l.id

                #Update returns the number of rows updated, which is useless to us for now
                Listing.objects.filter(id=listing_id).update(
                    title = title,
                    description = description,
                    photo_url = photo_url,
                    category = category,
                )
                saved_listing_id = listing_id

            #return value expected from this view
            return saved_listing_id

        else:
            return render(request, "auctions/manage_listing.html", {
                "error_message": "The form is not valid yet. Go back and edit values"
            })
    else:
        return render(request, "auctions/error.html", {
            "error_message": "This page is not meant to be accessed directly."
        })


#Add a bid to a listing
@login_required(login_url='/login')
def add_bid(request):
    l = Listing.objects.get(pk=request.POST.get("listing"))
    u = User.objects.get(pk=request.POST.get("user"))
    bid_value = ''
    next_bid = ''
    request.session["msg"]=''

    if request.method == "POST":
        bid_value = int(request.POST.get("bid"))
        # If first bid and greater than starting bid, save bid
        if l.bids_received.count() == 0 and bid_value >= int(l.starting_bid):
            Bid.objects.create(by_user=u, for_listing=l, bid_value=bid_value)
        #Save bid if bid greater than current bid
        else:
            if bid_value > l.current_bid:
                Bid.objects.create(by_user=u, for_listing=l, bid_value=bid_value)

        #Upate current bid to the bid value just saved.
        l.current_bid = bid_value
        l.save()

        messages.success(request, 'Bid was successfully added')
        return redirect("auctions:u_listing_detail", listing_id=l.id)

    else:
        return render(request, "auctions/listing_detail.html", {
            "listing": l,
        })

#Create a watchlist
@login_required(login_url='/login')
def watchlist(request):
    u = User.objects.get(pk=int(request.session.get('_auth_user_id')))
    form = NewWatchlistForm(request.POST)
    #if the user had no watchlist, capture the
    listing_to_add = request.GET.get('p', '')

    #Show the list of watchlists if user visiting page
    if request.method == "GET":
        return render(request, "auctions/watchlist.html", {
            "watchlist": u.watchlist.all(),
            "create_form": form
        })
    elif request.method == "POST":
        if form.is_valid():
            name = form.cleaned_data["name"]

commerce/auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block body %}
<h2>Categories</h2>

    {% for category in categories %}
      <p>{{category.name}}</p>
      <ul>
      {% for listing in category.listings.all %}
        <li> <a href="{% url 'auctions:u_listing_detail' listing.id %}"> {{listing.title}} --By:{{listing.by_user}} </a> </li>
      {% endfor %}
      </ul>
    {% endfor %}

    {%if uncategorized%}
    <p>Uncategorized</p>
    <ul>
      {% for listing in uncategorized %}
        <li> <a href="{% url 'auctions:u_listing_detail' listing.id %}"> {{listing.title}} --By:{{listing.by_user}} </a> </li>
      {% endfor %}
    </ul>
    {%endif%}


{% endblock %}

commerce/auctions/templates/auctions/create_listing.html
{% extends "auctions/layout.html" %}

{% block title %}
    Create New Auction Listing
{% endblock %}

{% block body %}
  <form action="{% url 'auctions:u_create_listing' %}" method="post">
      {% csrf_token %}
      <table>
      {{create_form.as_table}}
      </table>
      <input type="submit" value="Submit">
  </form>
{% endblock %}

commerce/auctions/templates/auctions/error.html
{% extends "auctions/layout.html" %}

{% block title %}
    Error Page
{% endblock %}

{% block body %}
    <h2>Error Page</h2>
    {{error_message}}
{% endblock %}

commerce/auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}
{% load humanize %}

{% block body %}
    <h2>Active Listings</h2>
    <table>
      {% for listing in listings %}
      <tr>
        <td>
          {%if listing.photo_url %}
            <a href="{% url 'auctions:u_listing_detail' listing.id %}">
              <img src="{{listing.photo_url}}" height="200px" width="300px" style="object-fit:contain">
            </a>
          {%else%} No photo supplied {%endif%}
        </td>
        <td valign="top" style="padding:10px;">
          <a href="{% url 'auctions:u_listing_detail' listing.id %}"><h4>{{listing.title}}</h4></a>
          <p>Starting Price: ${{listing.starting_bid|floatformat:"2"|intcomma}} </p>
          <p>{{listing.description}} </p>
          <p>Created: {{listing.created}}</p>
          <p>Current Price is <b>${{listing.current_bid|floatformat:"2"|intcomma}}</b></p>
        </td>
      </tr>
      {% endfor %}
    </table>
    <hr>
    {%if closed_listings%}
    <h2>Closed Listings</h2>
    <ul>
    {% for listing in closed_listings %}
      <li> <a href="{% url 'auctions:u_listing_detail' listing.id %}"> {{listing.title}} | By: {{listing.by_user}} </a> </li>
    {% endfor %}
    </ul>
    {%endif%}

{% endblock %}

commerce/auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">

    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
            </li>
            {% if user.is_authenticated %}
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'auctions:u_create_listing' %}">Create Listing</a>
              </li>

              <li class="nav-item">
                  <a class="nav-link" href="{% url 'auctions:u_watchlist' %}">My Watchlist</a>
              </li>

              <li class="nav-item">
                  <a class="nav-link" href="{% url 'auctions:u_categories' %}">Categories</a>
              </li>


                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

        <!--pre> {% filter force_escape %} {% debug %} {% endfilter %} </pre-->
    </body>
</html>

commerce/auctions/templates/auctions/listing_detail.html
{% extends "auctions/layout.html" %}
{% load humanize %}

{% block body %}
    <h2>Listing Detail</h2>

    {%if error_message%}
      {{error_message}}
    {%endif%}

    <table border="1">
      <tr>
        <td><h4>{{listing.title}}</h4></td>
        <td>
          {% if user.is_authenticated and listing.by_user.id == user.id %}
            <a href="{% url 'auctions:u_manage_listing' listing.id %}">Manage This listing</a>
          {%endif%}
        </td>
      </tr>
      {% if listing.active is False%}
      <tr>
        <td colspan="2" bgcolor="red" >
          <div style="color: white;">
            This listing is now closed.
          </div>
        </td>
      </tr>
      {%endif%}
      <tr>
        <td>
          {%if listing.photo_url %}
            <img src="{{listing.photo_url}}" height="200px" width="200px" style="object-fit:contain">
          {%else%}
            No photo supplied
          {%endif%}
        </td>
        <td>
          <p>{{listing.description}} </p>
          <p>Category:
            {%if listing.category.name %}
              {{listing.category.name}}
            {%else%}
              No category listed
            {%endif%}
          </p>
          <p>Starting Price: <b>${{listing.starting_bid|floatformat:"2"|intcomma}}</b> </p>
          {% if listing.active is True %}
            <p><b>{{listing.bids_received.all.count}}</b> bids so far. Current Bid is <b>${{listing.current_bid|floatformat:"2"|intcomma}}</b></p>
          {% elif listing.active is False %}
            {%if listing.bids_received.all.count > 0 %}
              {% for bid in listing.bids_received.all %}
                {% if bid.winning_bid %}
                  <div>Winner: {{bid.by_user.username}} </div>
                  <div>This item was sold for ${{bid.bid_value|floatformat:"2"|intcomma}} </div>
                {%endif%}
              {% endfor %}
            {%else%}
              No bids were received
            {%endif%}
          {% endif %}
        </td>
      </tr>

      {% if user.is_authenticated %}
      {% if listing.active %}
      <tr>
        <td><h6>Make a bid</h6></td>
        <td>
            <form action="{% url 'auctions:u_add_bid' %}" method="post">
                {% csrf_token %}
                <input type="number" name="bid" placeholder="Bid ${{next_bid}} or higher" min="{{next_bid}}" required>
                <input type="hidden" name="listing" value="{{listing.id}}"></input>
                <input type="hidden" name="user" value="{{user.id}}"></input>
                {{create_form.as_p}}
                <input type="submit" value="Submit">
            </form>
        </td>
      </tr>
      <tr>
        <td><h6>Watch this item</h6></td>
        <td>
          <form action="{% url 'auctions:u_add_to_watchlist' listing.id %}" method="post">
              {% csrf_token %}
              {%if user.watchlist.count > 0%}
              <select name="watchlist">
                  {% for watchlist in user.watchlist.all %}
                      <option value="{{ watchlist.id }}">{{ watchlist.name }}</option>
                  {% endfor %}
              </select>
              {%endif%}
              <input type="hidden" name="user" value="{{user.id}}"></input>
              {{create_form.as_p}}
              <input type="submit" value="Add item to watchlist">
          </form>

        </td>
      </tr>
      {%endif%}

      <tr>
          <td colspan="2">
            <h6>Discuss this item  </h6>
          </td>
      </tr>
      {% for comment in listing.comments.all reversed%}
      <tr>
          <td colspan="2">
            by:{{comment.by_user.username}} : {{comment.content}}
          </td>
      </tr>
      {% endfor %}

      {% if listing.active %}
      <tr>
        <td colspan="2">
          <form action="{% url 'auctions:u_add_comment' listing.id%}" method="post">
            {% csrf_token %}
            <textarea name="comment_body" rows="4" cols="80"></textarea>
            <p><input type="submit" value="Add comment"></p>
          </form>
          <!-- Show all previous comments made -->
        </td>
      </tr>
      {%endif%}

    </table>

    {% else %}
        <p>Sign in to bid, comment etc. Have fun shopping!</p>
    {% endif %}

{% endblock %}

commerce/auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>

{% endblock %}

commerce/auctions/templates/auctions/manage_listing.html
{% extends "auctions/layout.html" %}

{% block title %}
    Manage Auction Listing
{% endblock %}


{% block body %}

  {% if user.is_authenticated %}
      <h1>Manage auction listing </h1>
      {% if listing.active == True %}
        <form action="{% url 'auctions:u_close_listing' listing.id %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Close this listing">
        </form>
        <hr>
      {%else%}
        <p>This listing is closed. Go back to active listings and happy bidding.</p>
      {%endif%}


      {% if listing.active == True %}
        <fieldset>
      {% else %}
        <fieldset disabled>
      {% endif %}
        <form action="{% url 'auctions:u_manage_listing' listing.id %}" method="post">
            {% csrf_token %}
            <table>
            {{create_form.as_table}}
            </table>
            <input type="submit" value="Submit changes">
        </form>
    </fieldset>

  {% else %}
      You must be signed in to create listings.
  {% endif %}

{% endblock %}

commerce/auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>

{% endblock %}

commerce/auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Watchlist</h2>

  <h3>{{message}}</h3>

    {% if user.is_authenticated %}
    <p>You can have multiple watchlists, to keep track of items.</p>

      <ol>
        {% for watchitem in watchlist %}
          <li>{{watchitem.name}} (<a href="{% url 'auctions:u_delete_watchlist' watchitem.id %}">Delete this watchlist</a>)
          {% if watchitem.listings.count > 0 %}
          <ul>
            {%for listing in watchitem.listings.all %}
              <li>
                <a href="{% url 'auctions:u_listing_detail' listing.id %}"> {{listing.title}} </a>
                (<a href="{% url 'auctions:u_unwatch_listing' watchitem.id listing.id%}">stop watching this item</a>)
              </li>
            {%endfor%}
          </ul>
          {% else %}
            <ul><li>No items to watch yet. Lets add some <a href="/">listings</a> to watch</li></ul>
          {% endif %}
          <p></p>
        {%endfor%}
      </ol>

        <hr>
        <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#createWatchlistForm" aria-expanded="false" aria-controls="createWatchlistForm">
          Add another Watchlist
        </button>

          <div class="collapse" id="createWatchlistForm">
            <div class="card card-body">
              <form action="{% url 'auctions:u_watchlist' %}" method="post">
                  {% csrf_token %}
                  Watchlist Name: {{create_form.name}}
                  <input type="hidden" name="user" value="{{user.id}}"></input>
                  <input type="submit" value="Submit">
              </form>
            </div>
          </div>
    {% else %}
        You must be signed in to create a watchlist.
    {% endif %}

{% endblock %}